### ISSUE TITLE
Firefox blocks Metamask at CSP

### ISSUE THREAD

**Issue by jaerith** [spruceid/siwe#10]
Great job!  But I ran into some problems.  When I run the server and go to localhost:4361, the WalletConnect option brings up a prompt, but the Metamask one does nothing.  😦  I tried it on both Chrome v94 and Firefox v94 on a Mac.

**Comment by jaerith** [comment]
Looks like it's hanging on the line:

        await metamask.request({
            method: 'eth_requestAccounts',
        });

**Comment by wyc** [comment]
@jaerith sorry to hear that it's not working smoothly for you! Do any other apps using MetaMask work for you? You can try this one: https://web3modal.com/

We use web3modal under the hood.

**Comment by jaerith** [comment]
Interesting...I'm able to sign into the web3modal site without any issue.

**Comment by dcato98** [comment]
I'm experiencing this too, running Firefox v94 on Ubuntu. Metamask works fine on the web3modal site. This error message gets logged in the console:
```
Uncaught (in promise) TypeError: metamask is undefined
    signIn providers.ts:35
    __awaiter bundle.js:95800
    __awaiter bundle.js:95796
    signIn providers.ts:28
    ts providers.ts:176
```

**Comment by w4ll3** [comment]
@jaerith @dcato98 Do you have any other wallets installed?

**Comment by dcato98** [comment]
No, only metamask. See update 2 in my previous message though, I missed an earlier error in the console.

**Comment by dcato98** [comment]
I've never dealt with CSP before, but a quick google suggested adding this line to the head tag in index.html might fix the answer alas it does not.
`<meta http-equiv="Content-Security-Policy" content="script-src 'self';" />`

**Comment by w4ll3** [comment]
I'll dig into it a little further, but for this specific setup it wouldn't work, we have to set the CSP at `Helmet`. Does metamask work [here](https://notepad.spruceid.xyz/)?

**Comment by w4ll3** [comment]
This is related to (this)[https://github.com/MetaMask/metamask-extension/issues/3133] open issue.

**Comment by dcato98** [comment]
From the commentary in the issue you linked above, the easy-but-unsatisfying fix is to omit the Content Security Policy.

I tested this out and indeed, after commenting out the CSP in index.ts (i.e. `app.use(Helmet(...))`), metamask now works as expected.

For those looking for a fix that doesn't reduce security, there were a few slightly more complicated suggestions in the issue mentioned in the previous post for working around this.

**Comment by jaerith** [comment]
Confirmed!  Thanks @dcato98, commenting out the usage of Helmet got it to work.

The million dollar question is this: how does this Notepad example differ from the online voting demo when it comes to CSP, since that one does work in Mozilla?

**Comment by w4ll3** [comment]
The issue occurs only when CSP is applied to headers, since the content from the Notepad example is served directly from the express application `Helmet` filter those, that's not the case for login.xyz the API is quite similar but the files are not served from the API.

**Comment by jaerith** [comment]
Thanks for the answer, @w4ll3!  So we should avoid using Firefox for the time being and use another browser instead, like Chrome?

**Comment by w4ll3** [comment]
You could do that, or remove Helmet.

**Comment by jaerith** [comment]
Thanks again!
