### ISSUE TITLE
Changing `issuedAt` from optional to required breaks semver and downstream consumers

### ISSUE THREAD

**Issue by joewagner** [spruceid/siwe#135]
Specifically, removing [this check](https://github.com/spruceid/siwe/pull/127#discussion_r1004804589_) would indicate a major version bump i believe.

 Related issue: https://github.com/tablelandnetwork/js-tableland/pull/225

**Comment by wyc** [comment]
Hi @joewagner, this check was reinstated in https://github.com/spruceid/siwe/pull/134, published as 2.1.3, and 2.1.2 was deprecated accordingly. I'm also noting that the release is still tagged as `beta` on npm as we work through issues like this. Your input is much appreciated, thanks.

These changes were the result of recommended improvements from a recent security audit, and we will be publishing a complete release process for this library shortly (including maturity of beta releases, and promotion criteria to exit beta).

Thanks for your vigilance and patience, and apologies for the inconvenience. Please let us know if this worked for you.

**Comment by joewagner** [comment]
Awesome!! Thanks for creating and managing this excellent resource for the community 🙏 🙏
