### ISSUE TITLE
Support signing in with Argent

### ISSUE THREAD

**Issue by morleyzhi** [spruceid/siwe#137]
This would allow Gnosis safes and Argent wallets to sign in.

See also:
- https://eips.ethereum.org/EIPS/eip-1271
- https://github.com/authereum/is-valid-signature

**Comment by w4ll3** [comment]
Hello, siwe always supported EIP-1271 (All you need is to setup a provider). Is this still an issue for you? Also we are aware of some problems with Argent and WalletConnect V2, but that's not related to `siwe`.

**Comment by obstropolos** [comment]
Closing here.
