### ISSUE TITLE
Cannot read properties of undefined (reading 'decode') using SiweMessage

### ISSUE THREAD

**Issue by jpangelle** [spruceid/siwe#154]
### Code
```tsx
import { SiweMessage } from 'siwe'

const loginWithEvm = async (address: string, signer: any) => {
  const nonce = 'some-random-string'
  const domain = window.location.host
  const origin = window.location.origin
  const message = new SiweMessage({
    domain,
    address,
    statement: 'Please sign to authenticate your wallet',
    uri: origin,
    version: '1',
    chainId: 1,
    nonce,
})

const siweMessage = message.prepareMessage()
const signedMessage = await signer?.signMessage(siweMessage)

...
}
```

When the webapp initializes, a runtime error is thrown that white screens the entire app:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'decode') vendor.73b1ba86.js:1013 
    at Object.decode (vendor.73b1ba86.js:1013:49739)
    at wt (vendor.73b1ba86.js:1017:5788)
    at converter$1.decode (vendor.73b1ba86.js:1017:5987)
    at new ye (vendor.73b1ba86.js:1624:221)
    at GrammarApi.generateApi (vendor.73b1ba86.js:1764:50)
    at vendor.73b1ba86.js:1764:323
```

Debugging this has been extremely difficult. Any ideas on what the issue can be?

node: v16
app's [package.json](https://github.com/centrifuge/apps/blob/main/centrifuge-app/package.json)

**Comment by w4ll3** [comment]
shouldn't your nonce be only `nonce` instead of `nonce.nonce`? Also it's invalid, there should be no spaces in your nonce. https://eips.ethereum.org/EIPS/eip-4361#message-field-descriptions
> `nonce` is a randomized token typically chosen by the relying party and used to prevent replay attacks, at least 8 alphanumeric characters.

**Comment by jpangelle** [comment]
Ah ma bad. For the sake of this GitHub Issue, I genericized the code. I will update the snippet to be a valid nonce.

**Comment by w4ll3** [comment]
By the error message I would dare say it's related to the ABNF parser, do you have Node's Buffer as a polyfill?

**Comment by jpangelle** [comment]
> By the error message I would dare say it's related to the ABNF parser, do you have Node's Buffer as a polyfill? Also I'm not really sure about your use case / project, but you might also be interested at [SSX](https://docs.ssx.id).

It appears that we are polyfilling: https://github.com/centrifuge/apps/blob/main/centrifuge-app/vite.config.ts#L44

**Comment by cryptoKevinL** [comment]
Has this every been solved @jpangelle ?  I have the same issue, I'm not sure how to resolve it.  I just need the prepareMessage function as well.

**Comment by felixdenoix** [comment]
Hi,
Sorry to necrobump as well but I have the same issue. I'm on a nuxt@3 project and I thought i had all the necessary polyfills. @jpangelle, could you share your solution around here ? 

Nuxt config file for reference if it can be of any use:

```typescript
import { polyfillNode } from "esbuild-plugin-polyfill-node";
import inject from '@rollup/plugin-inject';

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({

  ssr: false,

  vite: {
    optimizeDeps: {

      include: ['siwe/*'],
      esbuildOptions: {
        define: {
          global: 'globalThis',
        },
        plugins: [
       	  polyfillNode({
            globals: {
              buffer: true
            },
          }),
        ],
      },
    },
    build: {
      target: 'esnext',
      commonjsOptions: {
        transformMixedEsModules: true,
      },
      rollupOptions: {
        plugins: [inject({ Buffer: ['buffer', 'Buffer'] })],
      }
    },
    resolve: {
      alias: {
        // polyfills
        'readable-stream': 'vite-compatible-readable-stream',
        stream: 'vite-compatible-readable-stream',
      },
    },
  },
});

```

**Comment by cryptoKevinL** [comment]
@felixdenoix I ended up just doing the SIWE manually - you can check any of the code at https://github.com/Wallet-Chat/walletchatFE/blob/4d7a7b461c32100d49f643f932fcd46345ca6139/src/context/WalletProvider.tsx#L628

**Comment by felixdenoix** [comment]
Found the issue: 
https://github.com/spruceid/siwe/issues/165
The new version of the package causing the issue was released 5 hours ago.

adding this to the `package.json` fixed the issue
```
  "overrides": {
    "siwe": {
      "apg-js": "^4.2.0"
    }
  }
```

**Comment by klugjo** [comment]
Thanks for much for this. 

I ended up having to use:

```
"overrides": {
    "@spruceid/siwe-parser": {
      "apg-js": "4.2.0"
    }
  }
```

for siwe 1.4.2
