### ISSUE TITLE
add PFP verification by ForeverPFP

### ISSUE THREAD

**Issue by PirateCode-eth** [spruceid/siwe#155]
Hi, I am PirateCode, CoFounder of BendDAO and a PFP user, would like to share this repo which I think can help for showing verified PFP avatar data for a ethereum ID:
https://github.com/ForeverPFP/ForeverPFP

https://twitter.com/PirateCode_ETH/status/1641690277193842688

Anyone dev interests on this? welcome to comment or share your thoughts about this.

**Comment by obstropolos** [comment]
Hey - this is interesting but I don't think it would go into this library (trying to make it as lightweight as possible!) 

However, we might be interesting in incorporating this into [SSX](docs.ssx.id) as a flag to ensure an avatar is a verified PFP!

**Comment by PirateCode-eth** [comment]
Wow, looks forward it. Once we are ready will let you know, and let’s push
web3 forward🫡

**Comment by PirateCode-eth** [comment]
> 

And maybe the PFP verification if you interests in it, cos the PFP may be just a copycat with same image metadata to confusing people.

https://github.com/ForeverPFP/ForeverPFP#what-is-pfp-community-verification

**Comment by obstropolos** [comment]
Closing this here - it may be the case of adding this to something more feature rich such as SSX
