### ISSUE TITLE
ethers import problem

### ISSUE THREAD

**Issue by adust09** [spruceid/siwe#163]
### What happend
From my side, an error like below shown. client.ts as well.
<img width="871" alt="スクリーンショット 2023-04-20 0 09 43" src="https://user-images.githubusercontent.com/47593288/233121733-bbd56353-9d2c-41f7-9d26-8c0e648de79c.png">
This is only my environment issue?

### Solution
It is possible to fix like this.`import { Provider } from 'ethers';`

**Comment by w4ll3** [comment]
Hello, I'm afraid it might be some config on your side. You should try deleting `node_modules` and re-installing, also note that `siwe` uses `npm` and not `yarn` (it should work with both but you never know).

**Comment by w4ll3** [comment]
Great!
