### ISSUE TITLE
Is there a cdn release? Want to try siwe with Flutter Web

### ISSUE THREAD

**Issue by rho-cassiopeiae** [spruceid/siwe#166]
Flutter Web can call JS code. I already use ethers.js and Metamask this way and now want to try adding siwe, but can't seem to find how to install it with <script> tag anywhere.

**Comment by w4ll3** [comment]
Unfortunately there is not.

**Comment by obstropolos** [comment]
Going to close this for now but will also note that there is a community member that made a `siwe-flutter` library!

https://github.com/onemoongate/Flutter-SIWE-Plugin
