### ISSUE TITLE
Custom logo when authenticating, possible?

### ISSUE THREAD

**Issue by JorensM** [spruceid/siwe#182]
Hello, I'm using SIWE to authenticate my users. I was wondering if it's possible to change the logo that is shown when a wallet is being signed-in.

<img width="211" alt="Screenshot 2023-08-14 at 15 51 04 (2)" src="https://github.com/spruceid/siwe/assets/17122123/5c9adec2-ecfe-49bf-ab0f-90ae04a38ff2">

As you can see here, the logo here is a bit out of bounds. Is it possible to change this? Or is this something that only the Wallet providers have control over?

**Comment by CRYPTO-GENIK** [comment]
The logo cropping is likely vendor-specific to each wallet but the image comes from ENS, right?

**Comment by jmacwhyte** [comment]
This is a wallet issue and has nothing to do with SIWE. Here is Metamask's page about it: https://docs.metamask.io/wallet/how-to/display/icon/

Like you theorized, it is similar to a favicon.

**Comment by JorensM** [comment]
@jmacwhyte Alright, thanks for the link! I'll close this now since it's not related to SIWE
