### ISSUE TITLE
'"ethers"' has no exported member named 'providers'

### ISSUE THREAD

**Issue by jiayuxiaochaoren** [spruceid/siwe#187]
When I build with `pnpm run build`,the following error occurred：
./node_modules/.pnpm/siwe@2.1.4_ethers@6.9.1/node_modules/siwe/lib/client.ts:7:10
Type error: '"ethers"' has no exported member named 'providers'. Did you mean 'Provider'?
parseIntegerNumber,
 } from '@spruceid/siwe-parser';
 import { providers } from 'ethers';
        ^
 import * as uri from 'valid-url';

import { getAddress, verifyMessage } from './ethersCompat';
Linting and checking validity of types  . ELIFECYCLE  Command failed with exit code 1.

**Comment by dankcellar** [comment]
Try it with ethers@5.x.x
