### ISSUE TITLE
Would like to reproduce

### ISSUE THREAD

**Issue by nglglhtr** [spruceid/siwe#19]
Is there any sdk or tutorial available for an independent project to be able to implement this spec?

**Comment by dcato98** [comment]
[These specs](https://github.com/ethereum/EIPs/blob/9a9c5d0abdaf5ce5c5dd6dc88c6d8db1b130e95b/EIPS/eip-4361.md) are linked at the bottom of the README.

I don't know of any sdk or tutorial to implement this, but I'd certainly be interested to hear about it too!

**Comment by w4ll3** [comment]
Hey guys you could check our [examples](/spruceid/siwe/tree/main/examples/notepad) folder for the notepad example, also it's [live here](https://notepad.spruceid.xyz/)

**Comment by w4ll3** [comment]
@nglglhtr @dcato98 was the example useful?
