### ISSUE TITLE
Should `issuedAt` for `SiweMessage` be a required member variable?

### ISSUE THREAD

**Issue by derekpierre** [spruceid/siwe#211]
According to the EIP4361 spec, `issuedAt` should be required - https://docs.login.xyz/general-information/siwe-overview/eip-4361#specification.

However, the value of the `issuedAt` member variable is optional - https://github.com/spruceid/siwe/blob/main/packages/siwe/lib/client.ts#L49.

This forces an undefined check before use. Is there a way to not have that be the case.

(caveat: Typescript is not my strong suit 😅 )

**Comment by chunningham** [comment]
the `issuedAt` field is optional in this implementation as it is ensured to exist when:
- parsing a message: the ABNF parser will ensure it is present in a message
- serialising to a message: the `toMessage()` function will assign an `issuedAt` time if one is not already present, so any generated message will contain it.
