### ISSUE TITLE
Any plans to do examples for other frameworks (eg. Blazor)?

### ISSUE THREAD

**Issue by vindberg** [spruceid/siwe#26]
Thanks for this initiative it is needed for faster adoption.

Instead of everyone doing the bulk work of creating models and endpoints it would help a lot with examples for each framework. Im currently working with .Net Blazor and interested in adding web3 as a sign-in option.

**Comment by obstropolos** [comment]
Hey @vindberg  - we absolutely plan on doing languages with associated examples for each framework! We recently released a bit more info on the planned languages / items in a blog post: 

https://blog.spruceid.com/sign-in-with-ethereum-support-updates/

**Comment by vindberg** [comment]
Great to hear c# is on the list. I will keep an eye on this repo, however do you have a timeline? Is funding secured?

**Comment by obstropolos** [comment]
Hey - at the moment we're wrapping up work on Rust, Ruby, and Elixir, with plans to go after a number of those languages next (likely with announcements as well) as to that progress. 

In terms of C# specifically, we're also collaborating with some folks from the Nethereum side that have a WIP implementation to get this moving! 

https://github.com/jaerith/siwe-nethereum

**Comment by vindberg** [comment]
Thanks for the link - great to see the Nethereum guys are doing work on this. Maybe I can even assist.
