### ISSUE TITLE
Invalid message Error when trying to validate

### ISSUE THREAD

**Issue by sudoFerraz** [spruceid/siwe#41]
Hello,

Currently when trying to validate a message received on the backend, the error: 

` Error: Invalid message: {"success":false,"state":103,"length":362,"matched":0,"maxMatched":5,"maxTreeDepth":15,"nodeHits":184,"inputLength":362,"subBegin":0,"subEnd":362,"subLength":362}
` 
is thrown,

Where can I see more resources regarding the "state:103" or more info regarding the message errors.

**Comment by sudoFerraz** [comment]
Realized I was using a previous version of SIWE from the notepad example, if you are hitting the same issue, be sure to update to siwe 1.0.0 on package.json and that the signature is not inside the SiweMessage anymore

**Comment by w4ll3** [comment]
Just for clarification this error was thrown by the ABNF parser, the state number could be other. In summary there was something wrong with the message generated (probably wrong version as you said).

**Comment by kent426** [comment]
FYI, in my case, there is some character like an apostrophe(') in my statement of the SiweMessage part, so it gave the above error.

**Comment by sudoFerraz** [comment]
@kent426 and anyone that also stumbled upon this, I realized that on the domain part, having a http://etc didn't worked because of one of the characters.
