### ISSUE TITLE
Is there support for templating engines like ejs, pug etc?

### ISSUE THREAD

**Issue by safisaleem** [spruceid/siwe#48]
I'm trying to use siwe with vanilla javascript (templating engine) and I was wondering if there's a way to use the following part in a script in html:

```
import { SiweMessage } from 'siwe';
const message = new SiweMessage({
    domain,
    address,
    statement,
    uri: origin,
    version: '1',
    chainId: '1',
    nonce: await res.text()
});
return message.prepareMessage();
```

**Comment by w4ll3** [comment]
I'm afraid not, you will need a bundler to add the polyfills. You can check the notepad example, run it and check the `public/bundle.js`, probably is what you're looking for.

**Comment by awoie** [comment]
@safisaleem did the provided solution work for you?

**Comment by safisaleem** [comment]
@awoie it did, yes. but not exactly like the example. all I needed from in my template was `SiweMessage` from the package. so i created a file with these 2 lines:

```
var siwe = require('siwe');
SiweMessage = siwe.SiweMessage;
```

and then used [webpack](https://www.npmjs.com/package/webpack) to convert that into a bundle. here's my webpack config:

```
const path = require('path');

module.exports = {
  entry: './my-file.js', //path to above file
  output: {
    path: path.resolve(__dirname, 'public', 'javascripts'),
    filename: 'bundle.js',
  },
};
```

**Comment by awoie** [comment]
Awesome, thanks. Closing this issue since the issue was solved.
