### ISSUE TITLE
Add EIP-55 validation

### ISSUE THREAD

**Issue by awoie** [spruceid/siwe#53]
EIP-55 validation should be added to parsing to avoid interop issues and test cases should be added.

**Comment by awoie** [comment]
The positive test cases should be fixed since they don't use EIP-55 addresses.

**Comment by w4ll3** [comment]
Addressed at #62

**Comment by Cali93** [comment]
As per the spec it SHOULD be EIP-55 compliant but it's not a MUST.
The current `SiweMessage` constructor throws if the provided address in the string message is all lowercase.
This brakes SIWE integrations when the user connects with wallets like Zerion.
Is there any chance we can add an optional param to bypass EIP55 validation ?
https://github.com/spruceid/siwe/pull/206/files

> address REQUIRED. The Ethereum address performing the signing. Its value **SHOULD** be conformant to mixed-case checksum address encoding specified in [ERC-55](https://eips.ethereum.org/EIPS/eip-55) where applicable.
