### ISSUE TITLE
Specific version of `ethers` package (5.5.1) is forced as a peer dependency

### ISSUE THREAD

**Issue by djnicholson** [spruceid/siwe#73]
See: https://github.com/spruceid/siwe/blob/6a9a8a22faaf7c1ad4b00125ce662aabf89fe360/packages/siwe/package.json#L30

I would like to use `siwe` in a repo that has `ethers@5.6.5` so cannot `npm i siwe`

**Comment by w4ll3** [comment]
Hi @djnicholson #70 addresses this exact issue, it'll be merged and deployed soon.

**Comment by djnicholson** [comment]
Confirmed fixed. Thanks.
