### ISSUE TITLE
Can't resolve 'siwe-parser'

### ISSUE THREAD

**Issue by Cali93** [spruceid/siwe#74]
![image](https://user-images.githubusercontent.com/32299095/167491953-c6776499-ba93-447f-9bb9-4211e4b96806.png)

Changes made in commit #66  aren't included in the latest package on npm as we can see on line 38 in 2.0.1 it still has the old code:
https://www.runpkg.com/?siwe@2.0.1/dist/client.js

**Comment by w4ll3** [comment]
2.0.2 should have the fix deployed, @Cali93 thanks!
