### ISSUE TITLE
Including newline (`\n`) in the statement

### ISSUE THREAD

**Issue by ajmnz** [spruceid/siwe#80]
Is there any way to add newlines to the statement?

Currently, if the statement is something like

```ts
const statement = "Welcome!\n Sign this message to continue"
```

When calling `new SiweMessage(message)` on the server to later verify the signature, it will fail with `Invalid message`. I believe this has something to do with how the parsing system works.

**Comment by ajmnz** [comment]
Pretty sure this line is what prevents using newlines in the statement

https://github.com/spruceid/siwe/blob/eb64c77e7d0f77f9b36eecb0f7f078797337b729/packages/siwe-parser/lib/abnf.ts#L10

**Comment by w4ll3** [comment]
https://eips.ethereum.org/EIPS/eip-4361#message-field-descriptions
