### ISSUE TITLE
Enforce that wallet which signed message is the same as message.address

### ISSUE THREAD

**Issue by sudoFerraz** [spruceid/siwe#92]
Hello spruce team,

Is there a way to enforce that the same wallet that was used on the message.address during SiweMessage creation is the one that signed it?
On other words, is it possible to derivate which wallet was used to sign from the signature?

Best Regards;

**Comment by sbihel** [comment]
This is precisely the point of the `verify` (formerly `validate`) function.

**Comment by sudoFerraz** [comment]
@sbihel Does validate also carries that functionality, or do we need to upgrade siwe and use verify to ensure the same address? Currently we use siwe: "1.1.2" from npm;

**Comment by sbihel** [comment]
Yes it does.
