### ISSUE TITLE
SiweMessage.regexFromMessage considerations

### ISSUE THREAD

**Issue by navigatrum** [spruceid/siwe#93]
Sorry guys, don't you believe it's somehow innatural to construct a  SiweMessage just to check the matching gruops of another message? I mean, would't it be handier if `regexFromMessage` was a static method?
It comes also in mind to make its arg optional, defaulting to `preapareMessage()`. In that case the need for the object would be justified. But if you want to check a message field after a SiweMessage has been successfully constructed, why reparsing the entire message, if all the fields are already available?

**Comment by awoie** [comment]
Thanks for raising that issue and good point. We are considering addressing this issue in one of our next releases.
