### ISSUE TITLE
Docs for Message::eip191_string are incorrect

### ISSUE THREAD

**Issue by WyseNynja** [spruceid/siwe#98]
The example for eip191_string is:

```
let eip191_string: String = message.eip191_string()?;
```

But the function returns `Result<Vec<u8>, fmt::Error>`

Given the function name ends in "string" I think something needs to change. Either rename to eip191_bytes or change the return type to ethers::types::Bytes.

**Comment by sbihel** [comment]
Would you mind opening this issue https://github.com/spruceid/siwe-rs please?

**Comment by WyseNynja** [comment]
Oops. Sorry about that. Making one there now.

**Comment by WyseNynja** [comment]
https://github.com/spruceid/siwe-rs/issues/40
